/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManagerRole;

/**
 *
 * @author rishika
 */

public class medicalMainPageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalMainJPanel
     */
    public medicalMainPageJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageHosp = new javax.swing.JButton();
        btnConfirmBooking = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblsysadmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnManageHosp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageHosp.setText("MANAGE HOSPITALS");
        add(btnManageHosp);
        btnManageHosp.setBounds(60, 270, 310, 50);

        btnConfirmBooking.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConfirmBooking.setText("CONFIRM BOOKINGS & ASSIGN ");
        btnConfirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmBookingActionPerformed(evt);
            }
        });
        add(btnConfirmBooking);
        btnConfirmBooking.setBounds(60, 350, 310, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("BACK");
        jPanel1.add(btnBack);
        btnBack.setBounds(70, 30, 110, 40);

        lblsysadmin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblsysadmin.setText("MEDICAL SERVICE MANAGER");
        jPanel1.add(lblsysadmin);
        lblsysadmin.setBounds(340, 30, 560, 44);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1460, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ar_2.gif"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(500, 170, 710, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmBooking;
    private javax.swing.JButton btnManageHosp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblsysadmin;
    // End of variables declaration//GEN-END:variables
}
